#!/bin/bash

pushdir=(
	/home/lucky/MyLib/darknet
	/home/lucky/MyLib/DBoW2
	/home/lucky/MyLib/g2o
	/home/lucky/MyLib/octomap
	/home/lucky/MyLib/shadowsocks
	/home/lucky/MyLib/OriginLib/octomap
	/home/lucky/workspace/src/humanoid
	/home/lucky/workspace/src/octomap
	/home/lucky/workspace/src/orb_slam
	/home/lucky/workspace/src/dataset
	/home/lucky/workspace/launch
	/home/lucky/workspace/shell
)

git_push()
{
	cd $1
	git add -A
	git commit -m "upload"
	git push -u origin master
}


for dir in ${pushdir[@]}
do
	git_push $dir
done
